CREATE TABLE pricing_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pricing_categories_code UNIQUE (code)
);

CREATE TABLE pricing_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(50) NOT NULL,
    material_code VARCHAR(50) NOT NULL,
    material_name VARCHAR(100) NOT NULL,
    multiplier NUMERIC(4,2) NOT NULL DEFAULT 1.00,
    base_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pricing_materials_category_material UNIQUE (category_code, material_code),
    CONSTRAINT fk_pricing_materials_categories
        FOREIGN KEY (category_code) REFERENCES pricing_categories (code) ON DELETE RESTRICT
);

CREATE TABLE pricing_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(50) NOT NULL,
    rule_name VARCHAR(100) NOT NULL,
    min_area_sqm NUMERIC(8,3) NOT NULL,
    max_area_sqm NUMERIC(8,3),
    price_per_sqm NUMERIC(12,2) NOT NULL,
    lamination_fee_per_sqm NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    note VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pricing_rules_category_min_area UNIQUE (category_code, min_area_sqm),
    CONSTRAINT ck_pricing_rules_area_range CHECK (max_area_sqm IS NULL OR max_area_sqm > min_area_sqm),
    CONSTRAINT fk_pricing_rules_categories
        FOREIGN KEY (category_code) REFERENCES pricing_categories (code) ON DELETE RESTRICT
);

CREATE INDEX idx_pricing_materials_category_material
    ON pricing_materials (category_code, material_code);

CREATE INDEX idx_pricing_rules_category_active_min_area
    ON pricing_rules (category_code, is_active, min_area_sqm);
